name: Exercise-07-08-tests-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Exercise-07-08-tests-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Prerequisite Setup
        run: |
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-Ex7-8.git ex7-8
          mv ex7-8/* .
          rm -rf ex7-8 .git .github

          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-Utils.git/ utils
          cd utils
          g++ printMessage.cpp -o printMessage
          chmod +x printMessage
          mv printMessage ..
          mv CodesToMessages.csv ..
          cd ..
          rm -rf utils

          git clone https://$GH_PAT@github.com//Cyber-Education-Center/python-tester-for-chess.git python-tester
          mv python-tester/test_cases.json .
          mv python-tester/test_runner.py .
          rm -rf python-tester .git .github
          
          cat <<EOF > results.json
          {
            "grades": {
              "uml": 0,
              "Kasparov": 0,
              "Scholars mate": 0,
              "Random moves": 0
            }
          }
          EOF
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or whatever version you want
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Verify Submission Files
        run: |
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-VerifySubmittedFiles.git verifysubmittedfiles
          cd verifysubmittedfiles
          go build .
          chmod +x filesverifier
          mv filesverifier ..
          cd .. && rm -rf verifysubmittedfiles

          ./filesverifier PreSubmissionChecker.txt 5
          ./filesverifier PreSubmissionChecker.txt 2
          ./filesverifier PreSubmissionChecker.txt 4
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}

      - name: Check UML Diagram
        run: |
          echo "Checking for UML diagram (uml.png)..."
          if ./filesverifier PreSubmissionChecker.txt 1; then score=100; else score=0; fi
          jq ".grades.uml = $score" results.json > tmp.json && mv tmp.json results.json

      - name: Compile the test
        run: |
          tree
          # collect all .cpp files inside Ex7-8Files (recursively)
          SRC=($(find Ex7-8Files -type f -name '*.cpp' | sort))
      
          # compile them all into Ex05.exe
          g++ "${SRC[@]}" -o chessTester.exe

          echo "Compiled -----------------------------"
          # sanity check
          file chessTester.exe
          chmod +x chessTester.exe

      - name: Run the test
        run: |
          python test_runner.py | tee test_output.txt

      - name: Update results.json
        run: |
          kasparov=$(grep "Kasparov:" test_output.txt | awk -F': ' '{print $2}' | tr -d ')')
          scholars=$(grep "Scholars mate:" test_output.txt | awk -F': ' '{print $2}' | tr -d ')')
          random=$(grep "Random moves:" test_output.txt | awk -F': ' '{print $2}' | tr -d ')')

          jq ".grades.Kasparov = $kasparov" results.json > tmp.json && mv tmp.json results.json
          jq ".grades.\"Scholars mate\" = $scholars" results.json > tmp.json && mv tmp.json results.json
          jq ".grades.\"Random moves\" = $random" results.json > tmp.json && mv tmp.json results.json

          echo "Updated results.json:"
          cat results.json

      - name: Summary
        if: always()
        run: |
          echo "All checks completed."
          total=$(jq '[.grades.uml] | add' results.json)
          avg=$(jq -n "($total / 100 * 100) | round")
          echo "Final score: $avg% ($total out of 100)"
          echo -n "Final results.json:"; cat results.json | tr -d '\n'
